[package]
name = "tci"
version = "0.1.0"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.70", default-features = false }
js-sys = "0.3.46"
wasm-bindgen-futures = "0.4.19"
wee_alloc = { version = "0.4.5" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
serde = { version = "1.0.59", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc"] }
serde_repr = { version = "0.1.7" }
strum = { version = "0.24.0", features = ["derive"] }
peg = { version = "0.8.0" }
hashbrown = { version = "0.9.1", features = ["serde"] }
unicode-width = "0.1.7"
aliu = "0.1.18"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libc-print = "0.1.16"

[dev-dependencies]
interloc = "0.1.3"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "z"
lto = true
