[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.160"
serde-wasm-bindgen = "0.5.0"
compiler = { path = "../compiler" }
wasm-bindgen = "0.2.84"
wee_alloc = "0.4.5"
